# Generated by Django 3.2.9 on 2021-12-10 18:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True)),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=50)),
                ('logradouro', models.CharField(max_length=300)),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.campus')),
            ],
        ),
        migrations.CreateModel(
            name='CursoCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.curso')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='cursos',
            field=models.ManyToManyField(to='cadastros.CursoCampus'),
        ),
        migrations.AddField(
            model_name='campus',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.endereco'),
        ),
        migrations.AddField(
            model_name='campus',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.instituicao'),
        ),
        migrations.CreateModel(
            name='AcaoAfirmativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('descricao', ckeditor.fields.RichTextField(verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.campus')),
            ],
        ),
    ]
