# Generated by Django 3.2.9 on 2021-12-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
