# Generated by Django 3.2.9 on 2022-01-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_campus_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='foto',
            field=models.ImageField(default=None, upload_to='fotos_campus/'),
        ),
    ]
