# Generated by Django 3.2.9 on 2021-12-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20211207_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.curso')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='cursos',
            field=models.ManyToManyField(to='cadastros.CursoCampus'),
        ),
    ]
