# Generated by Django 3.2.9 on 2021-12-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20211208_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acaoafirmativa',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
