# Generated by Django 4.0.1 on 2022-01-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_instituicao_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
