# Generated by Django 4.0.5 on 2022-10-01 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_campus_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocampus',
            name='descricao',
            field=ckeditor.fields.RichTextField(default=' ', verbose_name='Informações complementares'),
            preserve_default=False,
        ),
    ]
