# Generated by Django 4.0.5 on 2022-10-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_cursocampus_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursocampus',
            old_name='descricao',
            new_name='info_complementar',
        ),
    ]
