# Generated by Django 4.1.2 on 2022-10-26 14:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_cota'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='descricao',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='curso',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
