# Generated by Django 4.1.2 on 2022-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_campus_descricao_curso_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='vagas',
        ),
        migrations.AddField(
            model_name='cursocampus',
            name='vagas',
            field=models.IntegerField(default=0),
        ),
    ]
