# Generated by Django 4.2.5 on 2023-11-06 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_remove_curso_vagas_cursocampus_vagas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='foto',
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default=None, upload_to='fotos_campus/')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cadastros.campus')),
            ],
        ),
    ]
