# Generated by Django 4.2.5 on 2023-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_remove_campus_foto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='foto',
            field=models.ImageField(default=None, upload_to='fotos_campus/'),
        ),
    ]
